# Model Configuration
model_name_or_path: "FacebookAI/xlm-roberta-base"
max_seq_length: 512

# Training Configuration
learning_rate: 5.0e-5
batch_size: 80
total_steps: 600000
warmup_steps: 0

# Checkpointing Configuration
output_dir: "results/xlmr"
checkpoint_schedule:
  save_initial_checkpoint: true

# Experiment Tracking
wandb_project: "cpt-learning-dynamics"
wandb_run_name: "xlmr-xho"
